frappe.query_reports["Campaign Leaderboard"] = {
    "filters": [
        {
            "fieldname": "quick_range",
            "label": "Quick Range",
            "fieldtype": "Select",
            "options": [
                "",
                "Today",
                "Last 7 Days",
                "This Month",
                "Last 3 Months"
            ],
            "default": "Last 7 Days",
            "on_change": function() {
                let range = frappe.query_report.get_filter_value("quick_range");
                let today = frappe.datetime.get_today();
                let from_date, to_date = today;

                if (range === "Today") {
                    from_date = today;
                } else if (range === "Last 7 Days") {
                    from_date = frappe.datetime.add_days(today, -7);
                } else if (range === "This Month") {
                    from_date = frappe.datetime.month_start(today);
                } else if (range === "Last 3 Months") {
                    from_date = frappe.datetime.add_months(today, -3);
                }

                frappe.query_report.set_filter_value("from_date", from_date);
                frappe.query_report.set_filter_value("to_date", to_date);
                frappe.query_report.refresh();
            }
        },
        {
            "fieldname": "from_date",
            "label": "From Date",
            "fieldtype": "Date"
        },
        {
            "fieldname": "to_date",
            "label": "To Date",
            "fieldtype": "Date"
        }
    ],

    onload: function(report) {
        // Custom Excel button
        report.page.add_inner_button(__('📊 Export to Excel'), function() {
            frappe.query_report.download_xlsx();
        });

        // Custom PDF Export with Professional Styling
        report.page.add_inner_button(__('📑 Export to PDF'), function() {
            let company = frappe.defaults.get_user_default("Company") || "Your Company";
            let today = frappe.datetime.get_today();
            
            // Generate chart as base64 for PDF
            let chartCanvas = document.querySelector('.frappe-chart svg');
            let chartDataURL = '';
            if (chartCanvas) {
                // Convert SVG to canvas, then to base64
                let svgData = new XMLSerializer().serializeToString(chartCanvas);
                let canvas = document.createElement("canvas");
                let ctx = canvas.getContext("2d");
                let img = document.createElement("img");
                img.onload = function() {
                    canvas.width = img.width;
                    canvas.height = img.height;
                    ctx.drawImage(img, 0, 0);
                    chartDataURL = canvas.toDataURL("image/png");
                };
                img.src = "data:image/svg+xml;base64," + btoa(svgData);
            }

            let print_settings = {
                orientation: "Landscape",
                title: "WhatsApp Campaign Leaderboard Report",
                columns: [
                    {"label": "Campaign", "fieldname": "campaign", "width": 200},
                    {"label": "Total", "fieldname": "total_recipients", "width": 80},
                    {"label": "Delivered", "fieldname": "delivered", "width": 80},
                    {"label": "Failed", "fieldname": "failed", "width": 80},
                    {"label": "Success Rate %", "fieldname": "success_rate", "width": 120}
                ],
                add_header_row: 1,
                header_html: `
                    <div class="report-header" style="display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 20px;">
                        <div>
                            <h1 style="margin: 0; color: #333;">📊 WhatsApp Campaign Leaderboard</h1>
                            <p style="margin: 5px 0; color: #666;">${company}</p>
                        </div>
                        <div style="text-align: right;">
                            <p style="margin: 0; color: #666;">Report Date: ${today}</p>
                            <p style="margin: 0; color: #666;">Generated by ERPNext WhatsApp Integration</p>
                        </div>
                    </div>
                    ${chartDataURL ? `<div style="text-align: center; margin: 20px 0;"><img src="${chartDataURL}" style="max-width: 100%; height: 300px;" /></div>` : ''}
                `,
                add_totals_row: 0,
                page_break_after: 0
            };
            
            frappe.query_report.download_pdf(print_settings);
        });

        // Add drill-down functionality for chart clicks
        let chart_wrapper = report.page.find('.chart-container');
        if (chart_wrapper.length) {
            chart_wrapper.on('click', '.data-point', function(e) {
                let campaign = $(this).attr('data-campaign');
                if (campaign) {
                    frappe.call({
                        method: "whatsapp_integration.api.dashboard_actions.get_drilldown",
                        args: { campaign: campaign },
                        callback: function(r) {
                            if (!r.message) return;

                            let rows = r.message.map(rec => `
                                <tr>
                                    <td>${rec.party_name}</td>
                                    <td>${rec.number}</td>
                                    <td>${rec.status}</td>
                                    <td>${frappe.datetime.str_to_user(rec.sent_time)}</td>
                                    <td>
                                        <button class="btn btn-xs btn-secondary preview-btn" data-msg="${encodeURIComponent(rec.message)}">👁 Preview</button>
                                        ${rec.status === "Failed" ? 
                                            `<button class="btn btn-xs btn-danger retry-btn" data-id="${rec.name}">🔁 Retry</button>` : ""}
                                    </td>
                                </tr>
                            `).join("");

                            frappe.msgprint({
                                title: `📊 Campaign: ${campaign} - Recipients`,
                                message: `
                                    <button class="btn btn-sm btn-danger bulk-retry" style="margin-bottom:10px;" data-campaign="${campaign}">
                                        🔁 Retry All Failed in Campaign
                                    </button>
                                    <table class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th>Recipient</th>
                                                <th>Number</th>
                                                <th>Status</th>
                                                <th>Sent Time</th>
                                                <th>Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody>${rows}</tbody>
                                    </table>
                                `,
                                wide: true
                            });

                            // Attach handlers for preview and retry
                            $(".preview-btn").on("click", function() {
                                frappe.msgprint({
                                    title: "📩 Message Preview",
                                    message: decodeURIComponent($(this).data("msg")),
                                    indicator: "blue"
                                });
                            });

                            $(".retry-btn").on("click", function() {
                                let rec_id = $(this).data("id");
                                frappe.call({
                                    method: "whatsapp_integration.api.campaign.retry_recipient",
                                    args: { recipient_id: rec_id },
                                    callback: function(res) {
                                        frappe.show_alert({ message: res.message, indicator: 'green' });
                                    }
                                });
                            });

                            $(".bulk-retry").on("click", function() {
                                let campaign = $(this).data("campaign");
                                frappe.call({
                                    method: "whatsapp_integration.api.campaign.bulk_retry",
                                    args: { campaign: campaign },
                                    callback: function(res) {
                                        frappe.show_alert({ message: res.message, indicator: 'green' });
                                    }
                                });
                            });
                        }
                    });
                }
            });
        }
    }
};
